dist: trusty
sudo: required

language: node_js
node_js:
  - 'stable'
  - '6'
  - '4'

after_success:
  - npm run coverage

addons:
  apt:
    sources:
     - google-chrome

before_script:  
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
